import 'core-js/stable';
import 'regenerator-runtime/runtime';
import './assets/css/style.css';
import './assets/css/login.css';
import './assets/css/navbar.css';
import './assets/css/table.css';
import './assets/css/message.css';
import './assets/css/register.css';
import './login';
